export default {
  Thin: "Poppins-Thin",
  ThinItalic: "Poppins-ThinItalic",
  ExtraLight: "Poppins-ExtraLight",
  ExtraLightItalic: "Poppins-ExtraLightItalic",
  Light: "Poppins-Light",
  LightItalic: "Poppins-LightItalic",
  Regular: "Poppins-Regular",
  RegularItalic: "Poppins-RegularItalic",
  Medium: "Poppins-Medium",
  MediumItalic: "Poppins-MediumItalic",
  SemiBold: "Poppins-SemiBold",
  SemiBoldItalic: "Poppins-SemiBoldItalic",
  Bold: "Poppins-Bold",
  BoldItalic: "Poppins-BoldItalic",
  ExtraBold: "Poppins-ExtraBold",
  ExtraBoldItalic: "Poppins-ExtraBoldItalic",
  Black: "Poppins-Black",
  BlackItalic: "Poppins-BlackItalic",

  // Additional Font Variants
  ExtraThin: "Poppins-ExtraThin",
  ExtraThinItalic: "Poppins-ExtraThinItalic",
  UltraLight: "Poppins-UltraLight",
  UltraLightItalic: "Poppins-UltraLightItalic",
  Heavy: "Poppins-Heavy",
  HeavyItalic: "Poppins-HeavyItalic",
};
